name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: 'eu-central-1'

jobs:

  test-terraform-role:
    name: Test gha-terraform
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/gha-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS identity
        run: aws sts get-caller-identity


  test-packer-role:
    name: Test gha-packer
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/gha-packer
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS identity
        run: aws sts get-caller-identity


  test-backend-deploy-role:
    name: Test gha-backend-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/gha-backend-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS identity
        run: aws sts get-caller-identity


  test-frontend-release-role:
    name: Test gha-frontend-release
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/gha-frontend-release
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS identity
        run: aws sts get-caller-identity
